version: '3'
services:
  server:
    restart: always
    build: ../sample-service/.
    image: sample-service-image
    container_name: sample-service
    expose:
    - 3000
  nginx:
    restart: always
    image: nginx
    container_name: sample-web-server
    ports:
      - 4300:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
